# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminous', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
